################################################################
# Based on Frontend-Precommit-rules:                           #
# https://github.com/SUI-Components/frontend-pre-commit-rules  #
# https://github.com/sasstools/sass-lint/tree/master/docs/rules#
################################################################

files:
  # include: '**/*.s+(a|c)ss'
  ignore:
  - 'src/sass/_grid.sass'
  - 'src/sass/lib/**/*.*'
  - 'src/sass/helpers/**/*.*'
  - 'src/sass/generated/**/*.*'
options:
  formatter: stylish
  merge-default-rules: false
  max-warnings: 0
rules:
  border-zero: 1
  brace-style:
    - 0
    - allow-single-line: false
  clean-import-paths:
    - 0
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline:
    - 0
    - include: false
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 0
    - style: long
  hex-notation:
    - 0
    - style: lowercase
  id-name-format: 1
  indentation:
    - 0
    - size: tab
  leading-zero:
    - 0
    - include: false
  mixin-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 0
  nesting-depth:
    - 1
    - max-depth: 2
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 1
  no-important: 2
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-trailing-zero: 1
  no-transition-all: 1 #
  no-url-protocols: 0
  placeholder-in-extend: 1
  placeholder-name-format: 1
  property-sort-order: 0
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon: 1
  space-after-comma: 1
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 0
  variable-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1
